### ISSUE TITLE
Call to Node module failed with error

### ISSUE THREAD

**Issue by carnould** [badulescub/Demo#2]
Hi,

After fixed the pb with the server, Now i have pb with the Client:
Exception: Call to Node module failed with error: Prerendering failed because of error: Error: Cannot find module 'C:\Users\pc\Downloads\Demo\Demo\Client\ClientApp\dist\main-server'
at Function.Module._resolveFilename (module.js:470:15)
at Function.Module._load (module.js:418:25)
at Module.require (module.js:498:17)
at require (internal/module.js:20:19)
at findBootModule (C:\Users\pc\AppData\Local\Temp\tmp980B.tmp:111:17)
at findRenderToStringFunc (C:\Users\pc\AppData\Local\Temp\tmp980B.tmp:116:28)
at renderToStringImpl (C:\Users\pc\AppData\Local\Temp\tmp980B.tmp:75:51)
at C:\Users\pc\AppData\Local\Temp\tmp982B.tmp:113:19
at IncomingMessage.<anonymous> (C:\Users\pc\AppData\Local\Temp\tmp982B.tmp:132:38)
at emitNone (events.js:86:13)
Current directory is: C:\Users\pc\Downloads\Demo\Demo\Client
Microsoft.AspNetCore.NodeServices.HostingModels.HttpNodeInstance+<InvokeExportAsync>d__7.MoveNext()

I will try to find a way to fix it for next person who have this issue too.

**Comment by carnould** [comment]
I close the solution and start again the server and client, the client launch correctly.

**Comment by badulescub** [comment]
Please make sure you have restored NuGet packages on both projects and executed npm install on the client project.
